// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="inference_inference,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=18.087300,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3622,HLS_SYN_LUT=4934,HLS_VERSION=2022_1}" *)

module inference (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_dout,
        input_r_empty_n,
        input_r_read,
        output_r_din,
        output_r_full_n,
        output_r_write,
        conv_weights_0_address0,
        conv_weights_0_ce0,
        conv_weights_0_q0,
        conv_weights_1_address0,
        conv_weights_1_ce0,
        conv_weights_1_q0,
        conv_weights_2_address0,
        conv_weights_2_ce0,
        conv_weights_2_q0,
        conv_weights_3_address0,
        conv_weights_3_ce0,
        conv_weights_3_q0,
        conv_weights_4_address0,
        conv_weights_4_ce0,
        conv_weights_4_q0,
        conv_weights_5_address0,
        conv_weights_5_ce0,
        conv_weights_5_q0,
        conv_weights_6_address0,
        conv_weights_6_ce0,
        conv_weights_6_q0,
        conv_weights_7_address0,
        conv_weights_7_ce0,
        conv_weights_7_q0,
        conv_weights_8_address0,
        conv_weights_8_ce0,
        conv_weights_8_q0,
        conv_weights_9_address0,
        conv_weights_9_ce0,
        conv_weights_9_q0,
        conv_weights_10_address0,
        conv_weights_10_ce0,
        conv_weights_10_q0,
        conv_weights_11_address0,
        conv_weights_11_ce0,
        conv_weights_11_q0,
        conv_weights_12_address0,
        conv_weights_12_ce0,
        conv_weights_12_q0,
        conv_weights_13_address0,
        conv_weights_13_ce0,
        conv_weights_13_q0,
        conv_weights_14_address0,
        conv_weights_14_ce0,
        conv_weights_14_q0,
        conv_weights_15_address0,
        conv_weights_15_ce0,
        conv_weights_15_q0,
        conv_biases_0,
        conv_biases_1,
        conv_biases_2,
        conv_biases_3,
        conv_biases_4,
        conv_biases_5,
        conv_biases_6,
        conv_biases_7,
        conv_biases_8,
        conv_biases_9,
        conv_biases_10,
        conv_biases_11,
        conv_biases_12,
        conv_biases_13,
        conv_biases_14,
        conv_biases_15,
        pool_size,
        pool_stride,
        linear_weights_0_address0,
        linear_weights_0_ce0,
        linear_weights_0_q0,
        linear_weights_0_address1,
        linear_weights_0_ce1,
        linear_weights_0_q1,
        linear_weights_1_address0,
        linear_weights_1_ce0,
        linear_weights_1_q0,
        linear_weights_1_address1,
        linear_weights_1_ce1,
        linear_weights_1_q1,
        linear_weights_2_address0,
        linear_weights_2_ce0,
        linear_weights_2_q0,
        linear_weights_2_address1,
        linear_weights_2_ce1,
        linear_weights_2_q1,
        linear_weights_3_address0,
        linear_weights_3_ce0,
        linear_weights_3_q0,
        linear_weights_3_address1,
        linear_weights_3_ce1,
        linear_weights_3_q1,
        linear_weights_4_address0,
        linear_weights_4_ce0,
        linear_weights_4_q0,
        linear_weights_4_address1,
        linear_weights_4_ce1,
        linear_weights_4_q1,
        linear_weights_5_address0,
        linear_weights_5_ce0,
        linear_weights_5_q0,
        linear_weights_5_address1,
        linear_weights_5_ce1,
        linear_weights_5_q1,
        linear_weights_6_address0,
        linear_weights_6_ce0,
        linear_weights_6_q0,
        linear_weights_6_address1,
        linear_weights_6_ce1,
        linear_weights_6_q1,
        linear_weights_7_address0,
        linear_weights_7_ce0,
        linear_weights_7_q0,
        linear_weights_7_address1,
        linear_weights_7_ce1,
        linear_weights_7_q1,
        linear_weights_8_address0,
        linear_weights_8_ce0,
        linear_weights_8_q0,
        linear_weights_8_address1,
        linear_weights_8_ce1,
        linear_weights_8_q1,
        linear_weights_9_address0,
        linear_weights_9_ce0,
        linear_weights_9_q0,
        linear_weights_9_address1,
        linear_weights_9_ce1,
        linear_weights_9_q1,
        linear_weights_10_address0,
        linear_weights_10_ce0,
        linear_weights_10_q0,
        linear_weights_10_address1,
        linear_weights_10_ce1,
        linear_weights_10_q1,
        linear_weights_11_address0,
        linear_weights_11_ce0,
        linear_weights_11_q0,
        linear_weights_11_address1,
        linear_weights_11_ce1,
        linear_weights_11_q1,
        linear_weights_12_address0,
        linear_weights_12_ce0,
        linear_weights_12_q0,
        linear_weights_12_address1,
        linear_weights_12_ce1,
        linear_weights_12_q1,
        linear_weights_13_address0,
        linear_weights_13_ce0,
        linear_weights_13_q0,
        linear_weights_13_address1,
        linear_weights_13_ce1,
        linear_weights_13_q1,
        linear_weights_14_address0,
        linear_weights_14_ce0,
        linear_weights_14_q0,
        linear_weights_14_address1,
        linear_weights_14_ce1,
        linear_weights_14_q1,
        linear_weights_15_address0,
        linear_weights_15_ce0,
        linear_weights_15_q0,
        linear_weights_15_address1,
        linear_weights_15_ce1,
        linear_weights_15_q1,
        linear_biases_0,
        linear_biases_1,
        linear_biases_2,
        linear_biases_3,
        linear_biases_4,
        linear_biases_5,
        linear_biases_6,
        linear_biases_7,
        linear_biases_8,
        linear_biases_9,
        linear_biases_10,
        linear_biases_11,
        linear_biases_12,
        linear_biases_13,
        linear_biases_14,
        linear_biases_15
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] input_r_dout;
input   input_r_empty_n;
output   input_r_read;
output  [15:0] output_r_din;
input   output_r_full_n;
output   output_r_write;
output  [6:0] conv_weights_0_address0;
output   conv_weights_0_ce0;
input  [31:0] conv_weights_0_q0;
output  [6:0] conv_weights_1_address0;
output   conv_weights_1_ce0;
input  [31:0] conv_weights_1_q0;
output  [6:0] conv_weights_2_address0;
output   conv_weights_2_ce0;
input  [31:0] conv_weights_2_q0;
output  [6:0] conv_weights_3_address0;
output   conv_weights_3_ce0;
input  [31:0] conv_weights_3_q0;
output  [6:0] conv_weights_4_address0;
output   conv_weights_4_ce0;
input  [31:0] conv_weights_4_q0;
output  [6:0] conv_weights_5_address0;
output   conv_weights_5_ce0;
input  [31:0] conv_weights_5_q0;
output  [6:0] conv_weights_6_address0;
output   conv_weights_6_ce0;
input  [31:0] conv_weights_6_q0;
output  [6:0] conv_weights_7_address0;
output   conv_weights_7_ce0;
input  [31:0] conv_weights_7_q0;
output  [6:0] conv_weights_8_address0;
output   conv_weights_8_ce0;
input  [31:0] conv_weights_8_q0;
output  [6:0] conv_weights_9_address0;
output   conv_weights_9_ce0;
input  [31:0] conv_weights_9_q0;
output  [6:0] conv_weights_10_address0;
output   conv_weights_10_ce0;
input  [31:0] conv_weights_10_q0;
output  [6:0] conv_weights_11_address0;
output   conv_weights_11_ce0;
input  [31:0] conv_weights_11_q0;
output  [6:0] conv_weights_12_address0;
output   conv_weights_12_ce0;
input  [31:0] conv_weights_12_q0;
output  [6:0] conv_weights_13_address0;
output   conv_weights_13_ce0;
input  [31:0] conv_weights_13_q0;
output  [6:0] conv_weights_14_address0;
output   conv_weights_14_ce0;
input  [31:0] conv_weights_14_q0;
output  [6:0] conv_weights_15_address0;
output   conv_weights_15_ce0;
input  [31:0] conv_weights_15_q0;
input  [31:0] conv_biases_0;
input  [31:0] conv_biases_1;
input  [31:0] conv_biases_2;
input  [31:0] conv_biases_3;
input  [31:0] conv_biases_4;
input  [31:0] conv_biases_5;
input  [31:0] conv_biases_6;
input  [31:0] conv_biases_7;
input  [31:0] conv_biases_8;
input  [31:0] conv_biases_9;
input  [31:0] conv_biases_10;
input  [31:0] conv_biases_11;
input  [31:0] conv_biases_12;
input  [31:0] conv_biases_13;
input  [31:0] conv_biases_14;
input  [31:0] conv_biases_15;
input  [31:0] pool_size;
input  [31:0] pool_stride;
output  [3:0] linear_weights_0_address0;
output   linear_weights_0_ce0;
input  [31:0] linear_weights_0_q0;
output  [3:0] linear_weights_0_address1;
output   linear_weights_0_ce1;
input  [31:0] linear_weights_0_q1;
output  [3:0] linear_weights_1_address0;
output   linear_weights_1_ce0;
input  [31:0] linear_weights_1_q0;
output  [3:0] linear_weights_1_address1;
output   linear_weights_1_ce1;
input  [31:0] linear_weights_1_q1;
output  [3:0] linear_weights_2_address0;
output   linear_weights_2_ce0;
input  [31:0] linear_weights_2_q0;
output  [3:0] linear_weights_2_address1;
output   linear_weights_2_ce1;
input  [31:0] linear_weights_2_q1;
output  [3:0] linear_weights_3_address0;
output   linear_weights_3_ce0;
input  [31:0] linear_weights_3_q0;
output  [3:0] linear_weights_3_address1;
output   linear_weights_3_ce1;
input  [31:0] linear_weights_3_q1;
output  [3:0] linear_weights_4_address0;
output   linear_weights_4_ce0;
input  [31:0] linear_weights_4_q0;
output  [3:0] linear_weights_4_address1;
output   linear_weights_4_ce1;
input  [31:0] linear_weights_4_q1;
output  [3:0] linear_weights_5_address0;
output   linear_weights_5_ce0;
input  [31:0] linear_weights_5_q0;
output  [3:0] linear_weights_5_address1;
output   linear_weights_5_ce1;
input  [31:0] linear_weights_5_q1;
output  [3:0] linear_weights_6_address0;
output   linear_weights_6_ce0;
input  [31:0] linear_weights_6_q0;
output  [3:0] linear_weights_6_address1;
output   linear_weights_6_ce1;
input  [31:0] linear_weights_6_q1;
output  [3:0] linear_weights_7_address0;
output   linear_weights_7_ce0;
input  [31:0] linear_weights_7_q0;
output  [3:0] linear_weights_7_address1;
output   linear_weights_7_ce1;
input  [31:0] linear_weights_7_q1;
output  [3:0] linear_weights_8_address0;
output   linear_weights_8_ce0;
input  [31:0] linear_weights_8_q0;
output  [3:0] linear_weights_8_address1;
output   linear_weights_8_ce1;
input  [31:0] linear_weights_8_q1;
output  [3:0] linear_weights_9_address0;
output   linear_weights_9_ce0;
input  [31:0] linear_weights_9_q0;
output  [3:0] linear_weights_9_address1;
output   linear_weights_9_ce1;
input  [31:0] linear_weights_9_q1;
output  [3:0] linear_weights_10_address0;
output   linear_weights_10_ce0;
input  [31:0] linear_weights_10_q0;
output  [3:0] linear_weights_10_address1;
output   linear_weights_10_ce1;
input  [31:0] linear_weights_10_q1;
output  [3:0] linear_weights_11_address0;
output   linear_weights_11_ce0;
input  [31:0] linear_weights_11_q0;
output  [3:0] linear_weights_11_address1;
output   linear_weights_11_ce1;
input  [31:0] linear_weights_11_q1;
output  [3:0] linear_weights_12_address0;
output   linear_weights_12_ce0;
input  [31:0] linear_weights_12_q0;
output  [3:0] linear_weights_12_address1;
output   linear_weights_12_ce1;
input  [31:0] linear_weights_12_q1;
output  [3:0] linear_weights_13_address0;
output   linear_weights_13_ce0;
input  [31:0] linear_weights_13_q0;
output  [3:0] linear_weights_13_address1;
output   linear_weights_13_ce1;
input  [31:0] linear_weights_13_q1;
output  [3:0] linear_weights_14_address0;
output   linear_weights_14_ce0;
input  [31:0] linear_weights_14_q0;
output  [3:0] linear_weights_14_address1;
output   linear_weights_14_ce1;
input  [31:0] linear_weights_14_q1;
output  [3:0] linear_weights_15_address0;
output   linear_weights_15_ce0;
input  [31:0] linear_weights_15_q0;
output  [3:0] linear_weights_15_address1;
output   linear_weights_15_ce1;
input  [31:0] linear_weights_15_q1;
input  [31:0] linear_biases_0;
input  [31:0] linear_biases_1;
input  [31:0] linear_biases_2;
input  [31:0] linear_biases_3;
input  [31:0] linear_biases_4;
input  [31:0] linear_biases_5;
input  [31:0] linear_biases_6;
input  [31:0] linear_biases_7;
input  [31:0] linear_biases_8;
input  [31:0] linear_biases_9;
input  [31:0] linear_biases_10;
input  [31:0] linear_biases_11;
input  [31:0] linear_biases_12;
input  [31:0] linear_biases_13;
input  [31:0] linear_biases_14;
input  [31:0] linear_biases_15;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_read;
reg output_r_write;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [30:0] trunc_ln86_fu_512_p1;
reg   [30:0] trunc_ln86_reg_538;
wire   [30:0] trunc_ln86_1_fu_516_p1;
reg   [30:0] trunc_ln86_1_reg_543;
wire   [0:0] or_ln46_fu_532_p2;
reg   [0:0] or_ln46_reg_640;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_idle;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_ready;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read;
wire   [15:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_din;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_ce0;
wire   [6:0] grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_ce0;
wire    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start;
wire    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done;
wire    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_idle;
wire    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_ready;
wire    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read;
wire   [15:0] grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_din;
wire    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_idle;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_ready;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read;
wire   [15:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_din;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce1;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address0;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce0;
wire   [3:0] grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address1;
wire    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce1;
reg    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg;
reg   [8:0] ap_NS_fsm;
wire    ap_NS_fsm_state2;
wire    ap_CS_fsm_state3;
wire    conv_output_full_n;
reg    conv_output_write;
reg    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire   [15:0] conv_output_dout;
wire    conv_output_empty_n;
reg    conv_output_read;
wire    pool_output_full_n;
reg    pool_output_write;
reg    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state9;
wire   [15:0] pool_output_dout;
wire    pool_output_empty_n;
reg    pool_output_read;
wire   [0:0] icmp_ln46_fu_520_p2;
wire   [0:0] icmp_ln46_1_fu_526_p2;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_CS_fsm_state4;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
reg    ap_ST_fsm_state9_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
#0 grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg = 1'b0;
#0 grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg = 1'b0;
end

inference_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3 grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start),
    .ap_done(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done),
    .ap_idle(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_idle),
    .ap_ready(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_ready),
    .input_r_dout(input_r_dout),
    .input_r_empty_n(input_r_empty_n),
    .input_r_read(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read),
    .conv_output_din(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_din),
    .conv_output_full_n(conv_output_full_n),
    .conv_output_write(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write),
    .conv_weights_0_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_address0),
    .conv_weights_0_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_ce0),
    .conv_weights_0_q0(conv_weights_0_q0),
    .conv_weights_1_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_address0),
    .conv_weights_1_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_ce0),
    .conv_weights_1_q0(conv_weights_1_q0),
    .conv_weights_2_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_address0),
    .conv_weights_2_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_ce0),
    .conv_weights_2_q0(conv_weights_2_q0),
    .conv_weights_3_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_address0),
    .conv_weights_3_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_ce0),
    .conv_weights_3_q0(conv_weights_3_q0),
    .conv_weights_4_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_address0),
    .conv_weights_4_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_ce0),
    .conv_weights_4_q0(conv_weights_4_q0),
    .conv_weights_5_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_address0),
    .conv_weights_5_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_ce0),
    .conv_weights_5_q0(conv_weights_5_q0),
    .conv_weights_6_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_address0),
    .conv_weights_6_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_ce0),
    .conv_weights_6_q0(conv_weights_6_q0),
    .conv_weights_7_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_address0),
    .conv_weights_7_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_ce0),
    .conv_weights_7_q0(conv_weights_7_q0),
    .conv_weights_8_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_address0),
    .conv_weights_8_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_ce0),
    .conv_weights_8_q0(conv_weights_8_q0),
    .conv_weights_9_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_address0),
    .conv_weights_9_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_ce0),
    .conv_weights_9_q0(conv_weights_9_q0),
    .conv_weights_10_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_address0),
    .conv_weights_10_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_ce0),
    .conv_weights_10_q0(conv_weights_10_q0),
    .conv_weights_11_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_address0),
    .conv_weights_11_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_ce0),
    .conv_weights_11_q0(conv_weights_11_q0),
    .conv_weights_12_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_address0),
    .conv_weights_12_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_ce0),
    .conv_weights_12_q0(conv_weights_12_q0),
    .conv_weights_13_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_address0),
    .conv_weights_13_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_ce0),
    .conv_weights_13_q0(conv_weights_13_q0),
    .conv_weights_14_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_address0),
    .conv_weights_14_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_ce0),
    .conv_weights_14_q0(conv_weights_14_q0),
    .conv_weights_15_address0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_address0),
    .conv_weights_15_ce0(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_ce0),
    .conv_weights_15_q0(conv_weights_15_q0),
    .conv_biases_0_load(conv_biases_0),
    .conv_biases_1_load(conv_biases_1),
    .conv_biases_2_load(conv_biases_2),
    .conv_biases_3_load(conv_biases_3),
    .conv_biases_4_load(conv_biases_4),
    .conv_biases_5_load(conv_biases_5),
    .conv_biases_6_load(conv_biases_6),
    .conv_biases_7_load(conv_biases_7),
    .conv_biases_8_load(conv_biases_8),
    .conv_biases_9_load(conv_biases_9),
    .conv_biases_10_load(conv_biases_10),
    .conv_biases_11_load(conv_biases_11),
    .conv_biases_12_load(conv_biases_12),
    .conv_biases_13_load(conv_biases_13),
    .conv_biases_14_load(conv_biases_14),
    .conv_biases_15_load(conv_biases_15)
);

inference_inference_Pipeline_VITIS_LOOP_54_1 grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start),
    .ap_done(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done),
    .ap_idle(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_idle),
    .ap_ready(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_ready),
    .conv_output_dout(conv_output_dout),
    .conv_output_empty_n(conv_output_empty_n),
    .conv_output_read(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read),
    .pool_output_din(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_din),
    .pool_output_full_n(pool_output_full_n),
    .pool_output_write(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write),
    .pool_stride(trunc_ln86_1_reg_543),
    .pool_size(trunc_ln86_reg_538)
);

inference_inference_Pipeline_VITIS_LOOP_76_1 grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start),
    .ap_done(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done),
    .ap_idle(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_idle),
    .ap_ready(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_ready),
    .pool_output_dout(pool_output_dout),
    .pool_output_empty_n(pool_output_empty_n),
    .pool_output_read(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read),
    .output_r_din(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_din),
    .output_r_full_n(output_r_full_n),
    .output_r_write(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write),
    .linear_weights_15_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address0),
    .linear_weights_15_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce0),
    .linear_weights_15_q0(linear_weights_15_q0),
    .linear_weights_15_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address1),
    .linear_weights_15_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce1),
    .linear_weights_15_q1(linear_weights_15_q1),
    .linear_weights_14_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address0),
    .linear_weights_14_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce0),
    .linear_weights_14_q0(linear_weights_14_q0),
    .linear_weights_14_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address1),
    .linear_weights_14_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce1),
    .linear_weights_14_q1(linear_weights_14_q1),
    .linear_weights_13_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address0),
    .linear_weights_13_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce0),
    .linear_weights_13_q0(linear_weights_13_q0),
    .linear_weights_13_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address1),
    .linear_weights_13_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce1),
    .linear_weights_13_q1(linear_weights_13_q1),
    .linear_weights_12_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address0),
    .linear_weights_12_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce0),
    .linear_weights_12_q0(linear_weights_12_q0),
    .linear_weights_12_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address1),
    .linear_weights_12_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce1),
    .linear_weights_12_q1(linear_weights_12_q1),
    .linear_weights_11_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address0),
    .linear_weights_11_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce0),
    .linear_weights_11_q0(linear_weights_11_q0),
    .linear_weights_11_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address1),
    .linear_weights_11_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce1),
    .linear_weights_11_q1(linear_weights_11_q1),
    .linear_weights_10_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address0),
    .linear_weights_10_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce0),
    .linear_weights_10_q0(linear_weights_10_q0),
    .linear_weights_10_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address1),
    .linear_weights_10_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce1),
    .linear_weights_10_q1(linear_weights_10_q1),
    .linear_weights_9_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address0),
    .linear_weights_9_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce0),
    .linear_weights_9_q0(linear_weights_9_q0),
    .linear_weights_9_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address1),
    .linear_weights_9_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce1),
    .linear_weights_9_q1(linear_weights_9_q1),
    .linear_weights_8_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address0),
    .linear_weights_8_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce0),
    .linear_weights_8_q0(linear_weights_8_q0),
    .linear_weights_8_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address1),
    .linear_weights_8_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce1),
    .linear_weights_8_q1(linear_weights_8_q1),
    .linear_weights_7_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address0),
    .linear_weights_7_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce0),
    .linear_weights_7_q0(linear_weights_7_q0),
    .linear_weights_7_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address1),
    .linear_weights_7_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce1),
    .linear_weights_7_q1(linear_weights_7_q1),
    .linear_weights_6_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address0),
    .linear_weights_6_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce0),
    .linear_weights_6_q0(linear_weights_6_q0),
    .linear_weights_6_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address1),
    .linear_weights_6_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce1),
    .linear_weights_6_q1(linear_weights_6_q1),
    .linear_weights_5_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address0),
    .linear_weights_5_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce0),
    .linear_weights_5_q0(linear_weights_5_q0),
    .linear_weights_5_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address1),
    .linear_weights_5_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce1),
    .linear_weights_5_q1(linear_weights_5_q1),
    .linear_weights_4_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address0),
    .linear_weights_4_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce0),
    .linear_weights_4_q0(linear_weights_4_q0),
    .linear_weights_4_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address1),
    .linear_weights_4_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce1),
    .linear_weights_4_q1(linear_weights_4_q1),
    .linear_weights_3_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address0),
    .linear_weights_3_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce0),
    .linear_weights_3_q0(linear_weights_3_q0),
    .linear_weights_3_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address1),
    .linear_weights_3_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce1),
    .linear_weights_3_q1(linear_weights_3_q1),
    .linear_weights_2_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address0),
    .linear_weights_2_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce0),
    .linear_weights_2_q0(linear_weights_2_q0),
    .linear_weights_2_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address1),
    .linear_weights_2_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce1),
    .linear_weights_2_q1(linear_weights_2_q1),
    .linear_weights_1_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address0),
    .linear_weights_1_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce0),
    .linear_weights_1_q0(linear_weights_1_q0),
    .linear_weights_1_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address1),
    .linear_weights_1_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce1),
    .linear_weights_1_q1(linear_weights_1_q1),
    .linear_weights_0_address0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address0),
    .linear_weights_0_ce0(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce0),
    .linear_weights_0_q0(linear_weights_0_q0),
    .linear_weights_0_address1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address1),
    .linear_weights_0_ce1(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce1),
    .linear_weights_0_q1(linear_weights_0_q1),
    .linear_biases_0_load(linear_biases_0),
    .linear_biases_1_load(linear_biases_1),
    .linear_biases_2_load(linear_biases_2),
    .linear_biases_3_load(linear_biases_3),
    .linear_biases_4_load(linear_biases_4),
    .linear_biases_5_load(linear_biases_5),
    .linear_biases_6_load(linear_biases_6),
    .linear_biases_7_load(linear_biases_7),
    .linear_biases_8_load(linear_biases_8),
    .linear_biases_9_load(linear_biases_9),
    .linear_biases_10_load(linear_biases_10),
    .linear_biases_11_load(linear_biases_11),
    .linear_biases_12_load(linear_biases_12),
    .linear_biases_13_load(linear_biases_13),
    .linear_biases_14_load(linear_biases_14),
    .linear_biases_15_load(linear_biases_15)
);

inference_fifo_w16_d2_S conv_output_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_din),
    .if_full_n(conv_output_full_n),
    .if_write(conv_output_write),
    .if_dout(conv_output_dout),
    .if_empty_n(conv_output_empty_n),
    .if_read(conv_output_read)
);

inference_fifo_w16_d2_S pool_output_fifo_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_din),
    .if_full_n(pool_output_full_n),
    .if_write(pool_output_write),
    .if_dout(pool_output_dout),
    .if_empty_n(pool_output_empty_n),
    .if_read(pool_output_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state2) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state8)) begin
            grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg <= 1'b1;
        end else if ((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_ready == 1'b1)) begin
            grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        or_ln46_reg_640 <= or_ln46_fu_532_p2;
        trunc_ln86_1_reg_543 <= trunc_ln86_1_fu_516_p1;
        trunc_ln86_reg_538 <= trunc_ln86_fu_512_p1;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

always @ (*) begin
    if ((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done == 1'b0)) begin
        ap_ST_fsm_state9_blk = 1'b1;
    end else begin
        ap_ST_fsm_state9_blk = 1'b0;
    end
end

always @ (*) begin
    if (((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        conv_output_read = grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read;
    end else begin
        conv_output_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        conv_output_write = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write;
    end else begin
        conv_output_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        input_r_read = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read;
    end else begin
        input_r_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_write = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write;
    end else begin
        output_r_write = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        pool_output_read = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read;
    end else begin
        pool_output_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        pool_output_write = grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write;
    end else begin
        pool_output_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            if (((grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((or_ln46_reg_640 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            if (((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state2 = ap_NS_fsm[32'd1];

assign conv_weights_0_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_address0;

assign conv_weights_0_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_ce0;

assign conv_weights_10_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_address0;

assign conv_weights_10_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_ce0;

assign conv_weights_11_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_address0;

assign conv_weights_11_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_ce0;

assign conv_weights_12_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_address0;

assign conv_weights_12_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_ce0;

assign conv_weights_13_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_address0;

assign conv_weights_13_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_ce0;

assign conv_weights_14_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_address0;

assign conv_weights_14_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_ce0;

assign conv_weights_15_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_address0;

assign conv_weights_15_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_ce0;

assign conv_weights_1_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_address0;

assign conv_weights_1_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_ce0;

assign conv_weights_2_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_address0;

assign conv_weights_2_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_ce0;

assign conv_weights_3_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_address0;

assign conv_weights_3_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_ce0;

assign conv_weights_4_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_address0;

assign conv_weights_4_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_ce0;

assign conv_weights_5_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_address0;

assign conv_weights_5_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_ce0;

assign conv_weights_6_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_address0;

assign conv_weights_6_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_ce0;

assign conv_weights_7_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_address0;

assign conv_weights_7_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_ce0;

assign conv_weights_8_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_address0;

assign conv_weights_8_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_ce0;

assign conv_weights_9_address0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_address0;

assign conv_weights_9_ce0 = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_ce0;

assign grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start = grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg;

assign grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start = grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg;

assign grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg;

assign icmp_ln46_1_fu_526_p2 = (($signed(pool_stride) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign icmp_ln46_fu_520_p2 = (($signed(pool_size) < $signed(32'd1)) ? 1'b1 : 1'b0);

assign linear_weights_0_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address0;

assign linear_weights_0_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address1;

assign linear_weights_0_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce0;

assign linear_weights_0_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce1;

assign linear_weights_10_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address0;

assign linear_weights_10_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address1;

assign linear_weights_10_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce0;

assign linear_weights_10_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce1;

assign linear_weights_11_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address0;

assign linear_weights_11_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address1;

assign linear_weights_11_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce0;

assign linear_weights_11_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce1;

assign linear_weights_12_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address0;

assign linear_weights_12_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address1;

assign linear_weights_12_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce0;

assign linear_weights_12_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce1;

assign linear_weights_13_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address0;

assign linear_weights_13_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address1;

assign linear_weights_13_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce0;

assign linear_weights_13_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce1;

assign linear_weights_14_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address0;

assign linear_weights_14_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address1;

assign linear_weights_14_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce0;

assign linear_weights_14_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce1;

assign linear_weights_15_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address0;

assign linear_weights_15_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address1;

assign linear_weights_15_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce0;

assign linear_weights_15_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce1;

assign linear_weights_1_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address0;

assign linear_weights_1_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address1;

assign linear_weights_1_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce0;

assign linear_weights_1_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce1;

assign linear_weights_2_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address0;

assign linear_weights_2_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address1;

assign linear_weights_2_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce0;

assign linear_weights_2_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce1;

assign linear_weights_3_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address0;

assign linear_weights_3_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address1;

assign linear_weights_3_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce0;

assign linear_weights_3_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce1;

assign linear_weights_4_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address0;

assign linear_weights_4_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address1;

assign linear_weights_4_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce0;

assign linear_weights_4_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce1;

assign linear_weights_5_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address0;

assign linear_weights_5_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address1;

assign linear_weights_5_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce0;

assign linear_weights_5_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce1;

assign linear_weights_6_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address0;

assign linear_weights_6_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address1;

assign linear_weights_6_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce0;

assign linear_weights_6_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce1;

assign linear_weights_7_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address0;

assign linear_weights_7_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address1;

assign linear_weights_7_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce0;

assign linear_weights_7_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce1;

assign linear_weights_8_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address0;

assign linear_weights_8_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address1;

assign linear_weights_8_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce0;

assign linear_weights_8_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce1;

assign linear_weights_9_address0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address0;

assign linear_weights_9_address1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address1;

assign linear_weights_9_ce0 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce0;

assign linear_weights_9_ce1 = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce1;

assign or_ln46_fu_532_p2 = (icmp_ln46_fu_520_p2 | icmp_ln46_1_fu_526_p2);

assign output_r_din = grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_din;

assign trunc_ln86_1_fu_516_p1 = pool_stride[30:0];

assign trunc_ln86_fu_512_p1 = pool_size[30:0];

endmodule //inference
