-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
-- Version: 2022.1
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity inference is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_dout : IN STD_LOGIC_VECTOR (15 downto 0);
    input_r_empty_n : IN STD_LOGIC;
    input_r_read : OUT STD_LOGIC;
    output_r_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    output_r_full_n : IN STD_LOGIC;
    output_r_write : OUT STD_LOGIC;
    conv_weights_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_0_ce0 : OUT STD_LOGIC;
    conv_weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_1_ce0 : OUT STD_LOGIC;
    conv_weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_2_ce0 : OUT STD_LOGIC;
    conv_weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_3_ce0 : OUT STD_LOGIC;
    conv_weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_4_ce0 : OUT STD_LOGIC;
    conv_weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_5_ce0 : OUT STD_LOGIC;
    conv_weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_6_ce0 : OUT STD_LOGIC;
    conv_weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_7_ce0 : OUT STD_LOGIC;
    conv_weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_8_ce0 : OUT STD_LOGIC;
    conv_weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_9_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_9_ce0 : OUT STD_LOGIC;
    conv_weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_10_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_10_ce0 : OUT STD_LOGIC;
    conv_weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_11_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_11_ce0 : OUT STD_LOGIC;
    conv_weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_12_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_12_ce0 : OUT STD_LOGIC;
    conv_weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_13_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_13_ce0 : OUT STD_LOGIC;
    conv_weights_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_14_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_14_ce0 : OUT STD_LOGIC;
    conv_weights_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_weights_15_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
    conv_weights_15_ce0 : OUT STD_LOGIC;
    conv_weights_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    conv_biases_15 : IN STD_LOGIC_VECTOR (31 downto 0);
    pool_size : IN STD_LOGIC_VECTOR (31 downto 0);
    pool_stride : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_0_ce0 : OUT STD_LOGIC;
    linear_weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_0_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_0_ce1 : OUT STD_LOGIC;
    linear_weights_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_1_ce0 : OUT STD_LOGIC;
    linear_weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_1_ce1 : OUT STD_LOGIC;
    linear_weights_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_2_ce0 : OUT STD_LOGIC;
    linear_weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_2_ce1 : OUT STD_LOGIC;
    linear_weights_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_3_ce0 : OUT STD_LOGIC;
    linear_weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_3_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_3_ce1 : OUT STD_LOGIC;
    linear_weights_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_4_ce0 : OUT STD_LOGIC;
    linear_weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_4_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_4_ce1 : OUT STD_LOGIC;
    linear_weights_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_5_ce0 : OUT STD_LOGIC;
    linear_weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_5_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_5_ce1 : OUT STD_LOGIC;
    linear_weights_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_6_ce0 : OUT STD_LOGIC;
    linear_weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_6_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_6_ce1 : OUT STD_LOGIC;
    linear_weights_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_7_ce0 : OUT STD_LOGIC;
    linear_weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_7_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_7_ce1 : OUT STD_LOGIC;
    linear_weights_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_8_ce0 : OUT STD_LOGIC;
    linear_weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_8_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_8_ce1 : OUT STD_LOGIC;
    linear_weights_8_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_9_ce0 : OUT STD_LOGIC;
    linear_weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_9_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_9_ce1 : OUT STD_LOGIC;
    linear_weights_9_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_10_ce0 : OUT STD_LOGIC;
    linear_weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_10_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_10_ce1 : OUT STD_LOGIC;
    linear_weights_10_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_11_ce0 : OUT STD_LOGIC;
    linear_weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_11_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_11_ce1 : OUT STD_LOGIC;
    linear_weights_11_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_12_ce0 : OUT STD_LOGIC;
    linear_weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_12_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_12_ce1 : OUT STD_LOGIC;
    linear_weights_12_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_13_ce0 : OUT STD_LOGIC;
    linear_weights_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_13_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_13_ce1 : OUT STD_LOGIC;
    linear_weights_13_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_14_ce0 : OUT STD_LOGIC;
    linear_weights_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_14_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_14_ce1 : OUT STD_LOGIC;
    linear_weights_14_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_15_ce0 : OUT STD_LOGIC;
    linear_weights_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_weights_15_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
    linear_weights_15_ce1 : OUT STD_LOGIC;
    linear_weights_15_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_0 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_1 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_2 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_3 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_4 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_5 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_6 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_7 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_8 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_9 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_10 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_11 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_12 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_13 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_14 : IN STD_LOGIC_VECTOR (31 downto 0);
    linear_biases_15 : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of inference is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "inference_inference,hls_ip_2022_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg400-1,HLS_INPUT_CLOCK=50.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=18.087300,HLS_SYN_LAT=-1,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3622,HLS_SYN_LUT=4934,HLS_VERSION=2022_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal trunc_ln86_fu_512_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln86_reg_538 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln86_1_fu_516_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal trunc_ln86_1_reg_543 : STD_LOGIC_VECTOR (30 downto 0);
    signal or_ln46_fu_532_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln46_reg_640 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_idle : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_ready : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_address0 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_idle : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_ready : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_idle : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_ready : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_din : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce0 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address1 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce1 : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg : STD_LOGIC := '0';
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_NS_fsm_state2 : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal conv_output_full_n : STD_LOGIC;
    signal conv_output_write : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal conv_output_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal conv_output_empty_n : STD_LOGIC;
    signal conv_output_read : STD_LOGIC;
    signal pool_output_full_n : STD_LOGIC;
    signal pool_output_write : STD_LOGIC;
    signal grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal pool_output_dout : STD_LOGIC_VECTOR (15 downto 0);
    signal pool_output_empty_n : STD_LOGIC;
    signal pool_output_read : STD_LOGIC;
    signal icmp_ln46_fu_520_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln46_1_fu_526_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component inference_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_r_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        input_r_empty_n : IN STD_LOGIC;
        input_r_read : OUT STD_LOGIC;
        conv_output_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        conv_output_full_n : IN STD_LOGIC;
        conv_output_write : OUT STD_LOGIC;
        conv_weights_0_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_0_ce0 : OUT STD_LOGIC;
        conv_weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_1_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_1_ce0 : OUT STD_LOGIC;
        conv_weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_2_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_2_ce0 : OUT STD_LOGIC;
        conv_weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_3_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_3_ce0 : OUT STD_LOGIC;
        conv_weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_4_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_4_ce0 : OUT STD_LOGIC;
        conv_weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_5_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_5_ce0 : OUT STD_LOGIC;
        conv_weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_6_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_6_ce0 : OUT STD_LOGIC;
        conv_weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_7_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_7_ce0 : OUT STD_LOGIC;
        conv_weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_8_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_8_ce0 : OUT STD_LOGIC;
        conv_weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_9_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_9_ce0 : OUT STD_LOGIC;
        conv_weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_10_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_10_ce0 : OUT STD_LOGIC;
        conv_weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_11_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_11_ce0 : OUT STD_LOGIC;
        conv_weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_12_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_12_ce0 : OUT STD_LOGIC;
        conv_weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_13_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_13_ce0 : OUT STD_LOGIC;
        conv_weights_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_14_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_14_ce0 : OUT STD_LOGIC;
        conv_weights_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_weights_15_address0 : OUT STD_LOGIC_VECTOR (6 downto 0);
        conv_weights_15_ce0 : OUT STD_LOGIC;
        conv_weights_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
        conv_biases_15_load : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component inference_inference_Pipeline_VITIS_LOOP_54_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        conv_output_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        conv_output_empty_n : IN STD_LOGIC;
        conv_output_read : OUT STD_LOGIC;
        pool_output_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        pool_output_full_n : IN STD_LOGIC;
        pool_output_write : OUT STD_LOGIC;
        pool_stride : IN STD_LOGIC_VECTOR (30 downto 0);
        pool_size : IN STD_LOGIC_VECTOR (30 downto 0) );
    end component;


    component inference_inference_Pipeline_VITIS_LOOP_76_1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        pool_output_dout : IN STD_LOGIC_VECTOR (15 downto 0);
        pool_output_empty_n : IN STD_LOGIC;
        pool_output_read : OUT STD_LOGIC;
        output_r_din : OUT STD_LOGIC_VECTOR (15 downto 0);
        output_r_full_n : IN STD_LOGIC;
        output_r_write : OUT STD_LOGIC;
        linear_weights_15_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_15_ce0 : OUT STD_LOGIC;
        linear_weights_15_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_15_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_15_ce1 : OUT STD_LOGIC;
        linear_weights_15_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_14_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_14_ce0 : OUT STD_LOGIC;
        linear_weights_14_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_14_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_14_ce1 : OUT STD_LOGIC;
        linear_weights_14_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_13_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_13_ce0 : OUT STD_LOGIC;
        linear_weights_13_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_13_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_13_ce1 : OUT STD_LOGIC;
        linear_weights_13_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_12_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_12_ce0 : OUT STD_LOGIC;
        linear_weights_12_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_12_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_12_ce1 : OUT STD_LOGIC;
        linear_weights_12_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_11_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_11_ce0 : OUT STD_LOGIC;
        linear_weights_11_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_11_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_11_ce1 : OUT STD_LOGIC;
        linear_weights_11_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_10_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_10_ce0 : OUT STD_LOGIC;
        linear_weights_10_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_10_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_10_ce1 : OUT STD_LOGIC;
        linear_weights_10_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_9_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_9_ce0 : OUT STD_LOGIC;
        linear_weights_9_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_9_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_9_ce1 : OUT STD_LOGIC;
        linear_weights_9_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_8_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_8_ce0 : OUT STD_LOGIC;
        linear_weights_8_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_8_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_8_ce1 : OUT STD_LOGIC;
        linear_weights_8_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_7_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_7_ce0 : OUT STD_LOGIC;
        linear_weights_7_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_7_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_7_ce1 : OUT STD_LOGIC;
        linear_weights_7_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_6_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_6_ce0 : OUT STD_LOGIC;
        linear_weights_6_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_6_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_6_ce1 : OUT STD_LOGIC;
        linear_weights_6_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_5_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_5_ce0 : OUT STD_LOGIC;
        linear_weights_5_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_5_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_5_ce1 : OUT STD_LOGIC;
        linear_weights_5_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_4_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_4_ce0 : OUT STD_LOGIC;
        linear_weights_4_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_4_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_4_ce1 : OUT STD_LOGIC;
        linear_weights_4_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_3_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_3_ce0 : OUT STD_LOGIC;
        linear_weights_3_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_3_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_3_ce1 : OUT STD_LOGIC;
        linear_weights_3_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_2_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_2_ce0 : OUT STD_LOGIC;
        linear_weights_2_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_2_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_2_ce1 : OUT STD_LOGIC;
        linear_weights_2_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_1_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_1_ce0 : OUT STD_LOGIC;
        linear_weights_1_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_1_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_1_ce1 : OUT STD_LOGIC;
        linear_weights_1_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_0_address0 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_0_ce0 : OUT STD_LOGIC;
        linear_weights_0_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_weights_0_address1 : OUT STD_LOGIC_VECTOR (3 downto 0);
        linear_weights_0_ce1 : OUT STD_LOGIC;
        linear_weights_0_q1 : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_0_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_1_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_2_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_3_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_4_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_5_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_6_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_7_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_8_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_9_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_10_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_11_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_12_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_13_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_14_load : IN STD_LOGIC_VECTOR (31 downto 0);
        linear_biases_15_load : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component inference_fifo_w16_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (15 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (15 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;



begin
    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394 : component inference_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start,
        ap_done => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done,
        ap_idle => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_idle,
        ap_ready => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_ready,
        input_r_dout => input_r_dout,
        input_r_empty_n => input_r_empty_n,
        input_r_read => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read,
        conv_output_din => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_din,
        conv_output_full_n => conv_output_full_n,
        conv_output_write => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write,
        conv_weights_0_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_address0,
        conv_weights_0_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_ce0,
        conv_weights_0_q0 => conv_weights_0_q0,
        conv_weights_1_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_address0,
        conv_weights_1_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_ce0,
        conv_weights_1_q0 => conv_weights_1_q0,
        conv_weights_2_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_address0,
        conv_weights_2_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_ce0,
        conv_weights_2_q0 => conv_weights_2_q0,
        conv_weights_3_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_address0,
        conv_weights_3_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_ce0,
        conv_weights_3_q0 => conv_weights_3_q0,
        conv_weights_4_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_address0,
        conv_weights_4_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_ce0,
        conv_weights_4_q0 => conv_weights_4_q0,
        conv_weights_5_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_address0,
        conv_weights_5_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_ce0,
        conv_weights_5_q0 => conv_weights_5_q0,
        conv_weights_6_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_address0,
        conv_weights_6_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_ce0,
        conv_weights_6_q0 => conv_weights_6_q0,
        conv_weights_7_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_address0,
        conv_weights_7_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_ce0,
        conv_weights_7_q0 => conv_weights_7_q0,
        conv_weights_8_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_address0,
        conv_weights_8_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_ce0,
        conv_weights_8_q0 => conv_weights_8_q0,
        conv_weights_9_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_address0,
        conv_weights_9_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_ce0,
        conv_weights_9_q0 => conv_weights_9_q0,
        conv_weights_10_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_address0,
        conv_weights_10_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_ce0,
        conv_weights_10_q0 => conv_weights_10_q0,
        conv_weights_11_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_address0,
        conv_weights_11_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_ce0,
        conv_weights_11_q0 => conv_weights_11_q0,
        conv_weights_12_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_address0,
        conv_weights_12_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_ce0,
        conv_weights_12_q0 => conv_weights_12_q0,
        conv_weights_13_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_address0,
        conv_weights_13_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_ce0,
        conv_weights_13_q0 => conv_weights_13_q0,
        conv_weights_14_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_address0,
        conv_weights_14_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_ce0,
        conv_weights_14_q0 => conv_weights_14_q0,
        conv_weights_15_address0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_address0,
        conv_weights_15_ce0 => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_ce0,
        conv_weights_15_q0 => conv_weights_15_q0,
        conv_biases_0_load => conv_biases_0,
        conv_biases_1_load => conv_biases_1,
        conv_biases_2_load => conv_biases_2,
        conv_biases_3_load => conv_biases_3,
        conv_biases_4_load => conv_biases_4,
        conv_biases_5_load => conv_biases_5,
        conv_biases_6_load => conv_biases_6,
        conv_biases_7_load => conv_biases_7,
        conv_biases_8_load => conv_biases_8,
        conv_biases_9_load => conv_biases_9,
        conv_biases_10_load => conv_biases_10,
        conv_biases_11_load => conv_biases_11,
        conv_biases_12_load => conv_biases_12,
        conv_biases_13_load => conv_biases_13,
        conv_biases_14_load => conv_biases_14,
        conv_biases_15_load => conv_biases_15);

    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449 : component inference_inference_Pipeline_VITIS_LOOP_54_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start,
        ap_done => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done,
        ap_idle => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_idle,
        ap_ready => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_ready,
        conv_output_dout => conv_output_dout,
        conv_output_empty_n => conv_output_empty_n,
        conv_output_read => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read,
        pool_output_din => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_din,
        pool_output_full_n => pool_output_full_n,
        pool_output_write => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write,
        pool_stride => trunc_ln86_1_reg_543,
        pool_size => trunc_ln86_reg_538);

    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457 : component inference_inference_Pipeline_VITIS_LOOP_76_1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start,
        ap_done => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done,
        ap_idle => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_idle,
        ap_ready => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_ready,
        pool_output_dout => pool_output_dout,
        pool_output_empty_n => pool_output_empty_n,
        pool_output_read => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read,
        output_r_din => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_din,
        output_r_full_n => output_r_full_n,
        output_r_write => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write,
        linear_weights_15_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address0,
        linear_weights_15_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce0,
        linear_weights_15_q0 => linear_weights_15_q0,
        linear_weights_15_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address1,
        linear_weights_15_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce1,
        linear_weights_15_q1 => linear_weights_15_q1,
        linear_weights_14_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address0,
        linear_weights_14_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce0,
        linear_weights_14_q0 => linear_weights_14_q0,
        linear_weights_14_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address1,
        linear_weights_14_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce1,
        linear_weights_14_q1 => linear_weights_14_q1,
        linear_weights_13_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address0,
        linear_weights_13_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce0,
        linear_weights_13_q0 => linear_weights_13_q0,
        linear_weights_13_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address1,
        linear_weights_13_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce1,
        linear_weights_13_q1 => linear_weights_13_q1,
        linear_weights_12_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address0,
        linear_weights_12_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce0,
        linear_weights_12_q0 => linear_weights_12_q0,
        linear_weights_12_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address1,
        linear_weights_12_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce1,
        linear_weights_12_q1 => linear_weights_12_q1,
        linear_weights_11_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address0,
        linear_weights_11_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce0,
        linear_weights_11_q0 => linear_weights_11_q0,
        linear_weights_11_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address1,
        linear_weights_11_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce1,
        linear_weights_11_q1 => linear_weights_11_q1,
        linear_weights_10_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address0,
        linear_weights_10_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce0,
        linear_weights_10_q0 => linear_weights_10_q0,
        linear_weights_10_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address1,
        linear_weights_10_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce1,
        linear_weights_10_q1 => linear_weights_10_q1,
        linear_weights_9_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address0,
        linear_weights_9_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce0,
        linear_weights_9_q0 => linear_weights_9_q0,
        linear_weights_9_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address1,
        linear_weights_9_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce1,
        linear_weights_9_q1 => linear_weights_9_q1,
        linear_weights_8_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address0,
        linear_weights_8_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce0,
        linear_weights_8_q0 => linear_weights_8_q0,
        linear_weights_8_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address1,
        linear_weights_8_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce1,
        linear_weights_8_q1 => linear_weights_8_q1,
        linear_weights_7_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address0,
        linear_weights_7_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce0,
        linear_weights_7_q0 => linear_weights_7_q0,
        linear_weights_7_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address1,
        linear_weights_7_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce1,
        linear_weights_7_q1 => linear_weights_7_q1,
        linear_weights_6_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address0,
        linear_weights_6_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce0,
        linear_weights_6_q0 => linear_weights_6_q0,
        linear_weights_6_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address1,
        linear_weights_6_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce1,
        linear_weights_6_q1 => linear_weights_6_q1,
        linear_weights_5_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address0,
        linear_weights_5_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce0,
        linear_weights_5_q0 => linear_weights_5_q0,
        linear_weights_5_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address1,
        linear_weights_5_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce1,
        linear_weights_5_q1 => linear_weights_5_q1,
        linear_weights_4_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address0,
        linear_weights_4_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce0,
        linear_weights_4_q0 => linear_weights_4_q0,
        linear_weights_4_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address1,
        linear_weights_4_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce1,
        linear_weights_4_q1 => linear_weights_4_q1,
        linear_weights_3_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address0,
        linear_weights_3_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce0,
        linear_weights_3_q0 => linear_weights_3_q0,
        linear_weights_3_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address1,
        linear_weights_3_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce1,
        linear_weights_3_q1 => linear_weights_3_q1,
        linear_weights_2_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address0,
        linear_weights_2_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce0,
        linear_weights_2_q0 => linear_weights_2_q0,
        linear_weights_2_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address1,
        linear_weights_2_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce1,
        linear_weights_2_q1 => linear_weights_2_q1,
        linear_weights_1_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address0,
        linear_weights_1_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce0,
        linear_weights_1_q0 => linear_weights_1_q0,
        linear_weights_1_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address1,
        linear_weights_1_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce1,
        linear_weights_1_q1 => linear_weights_1_q1,
        linear_weights_0_address0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address0,
        linear_weights_0_ce0 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce0,
        linear_weights_0_q0 => linear_weights_0_q0,
        linear_weights_0_address1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address1,
        linear_weights_0_ce1 => grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce1,
        linear_weights_0_q1 => linear_weights_0_q1,
        linear_biases_0_load => linear_biases_0,
        linear_biases_1_load => linear_biases_1,
        linear_biases_2_load => linear_biases_2,
        linear_biases_3_load => linear_biases_3,
        linear_biases_4_load => linear_biases_4,
        linear_biases_5_load => linear_biases_5,
        linear_biases_6_load => linear_biases_6,
        linear_biases_7_load => linear_biases_7,
        linear_biases_8_load => linear_biases_8,
        linear_biases_9_load => linear_biases_9,
        linear_biases_10_load => linear_biases_10,
        linear_biases_11_load => linear_biases_11,
        linear_biases_12_load => linear_biases_12,
        linear_biases_13_load => linear_biases_13,
        linear_biases_14_load => linear_biases_14,
        linear_biases_15_load => linear_biases_15);

    conv_output_fifo_U : component inference_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_din,
        if_full_n => conv_output_full_n,
        if_write => conv_output_write,
        if_dout => conv_output_dout,
        if_empty_n => conv_output_empty_n,
        if_read => conv_output_read);

    pool_output_fifo_U : component inference_fifo_w16_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_din,
        if_full_n => pool_output_full_n,
        if_write => pool_output_write,
        if_dout => pool_output_dout,
        if_empty_n => pool_output_empty_n,
        if_read => pool_output_read);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_NS_fsm_state2) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_ready = ap_const_logic_1)) then 
                    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_ready = ap_const_logic_1)) then 
                    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_ready = ap_const_logic_1)) then 
                    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                or_ln46_reg_640 <= or_ln46_fu_532_p2;
                trunc_ln86_1_reg_543 <= trunc_ln86_1_fu_516_p1;
                trunc_ln86_reg_538 <= trunc_ln86_fu_512_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, or_ln46_reg_640, grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done, grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done, grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done, ap_CS_fsm_state3, ap_CS_fsm_state6, ap_CS_fsm_state9, ap_CS_fsm_state4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                if (((grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((or_ln46_reg_640 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                if (((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_NS_fsm_state2 <= ap_NS_fsm(1);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_fsm_state3_blk_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done)
    begin
        if ((grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done)
    begin
        if ((grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;

    ap_ST_fsm_state9_blk_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done)
    begin
        if ((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done, ap_CS_fsm_state9)
    begin
        if (((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done, ap_CS_fsm_state9)
    begin
        if (((grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    conv_output_read_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            conv_output_read <= grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_conv_output_read;
        else 
            conv_output_read <= ap_const_logic_0;
        end if; 
    end process;


    conv_output_write_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            conv_output_write <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_output_write;
        else 
            conv_output_write <= ap_const_logic_0;
        end if; 
    end process;

    conv_weights_0_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_address0;
    conv_weights_0_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_0_ce0;
    conv_weights_10_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_address0;
    conv_weights_10_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_10_ce0;
    conv_weights_11_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_address0;
    conv_weights_11_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_11_ce0;
    conv_weights_12_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_address0;
    conv_weights_12_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_12_ce0;
    conv_weights_13_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_address0;
    conv_weights_13_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_13_ce0;
    conv_weights_14_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_address0;
    conv_weights_14_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_14_ce0;
    conv_weights_15_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_address0;
    conv_weights_15_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_15_ce0;
    conv_weights_1_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_address0;
    conv_weights_1_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_1_ce0;
    conv_weights_2_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_address0;
    conv_weights_2_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_2_ce0;
    conv_weights_3_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_address0;
    conv_weights_3_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_3_ce0;
    conv_weights_4_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_address0;
    conv_weights_4_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_4_ce0;
    conv_weights_5_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_address0;
    conv_weights_5_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_5_ce0;
    conv_weights_6_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_address0;
    conv_weights_6_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_6_ce0;
    conv_weights_7_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_address0;
    conv_weights_7_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_7_ce0;
    conv_weights_8_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_address0;
    conv_weights_8_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_8_ce0;
    conv_weights_9_address0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_address0;
    conv_weights_9_ce0 <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_conv_weights_9_ce0;
    grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_ap_start_reg;
    grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start <= grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_ap_start_reg;
    grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_ap_start_reg;
    icmp_ln46_1_fu_526_p2 <= "1" when (signed(pool_stride) < signed(ap_const_lv32_1)) else "0";
    icmp_ln46_fu_520_p2 <= "1" when (signed(pool_size) < signed(ap_const_lv32_1)) else "0";

    input_r_read_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read, ap_CS_fsm_state3)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
            input_r_read <= grp_inference_Pipeline_VITIS_LOOP_22_1_VITIS_LOOP_23_2_VITIS_LOOP_25_3_fu_394_input_r_read;
        else 
            input_r_read <= ap_const_logic_0;
        end if; 
    end process;

    linear_weights_0_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address0;
    linear_weights_0_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_address1;
    linear_weights_0_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce0;
    linear_weights_0_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_0_ce1;
    linear_weights_10_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address0;
    linear_weights_10_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_address1;
    linear_weights_10_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce0;
    linear_weights_10_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_10_ce1;
    linear_weights_11_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address0;
    linear_weights_11_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_address1;
    linear_weights_11_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce0;
    linear_weights_11_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_11_ce1;
    linear_weights_12_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address0;
    linear_weights_12_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_address1;
    linear_weights_12_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce0;
    linear_weights_12_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_12_ce1;
    linear_weights_13_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address0;
    linear_weights_13_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_address1;
    linear_weights_13_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce0;
    linear_weights_13_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_13_ce1;
    linear_weights_14_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address0;
    linear_weights_14_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_address1;
    linear_weights_14_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce0;
    linear_weights_14_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_14_ce1;
    linear_weights_15_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address0;
    linear_weights_15_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_address1;
    linear_weights_15_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce0;
    linear_weights_15_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_15_ce1;
    linear_weights_1_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address0;
    linear_weights_1_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_address1;
    linear_weights_1_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce0;
    linear_weights_1_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_1_ce1;
    linear_weights_2_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address0;
    linear_weights_2_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_address1;
    linear_weights_2_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce0;
    linear_weights_2_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_2_ce1;
    linear_weights_3_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address0;
    linear_weights_3_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_address1;
    linear_weights_3_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce0;
    linear_weights_3_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_3_ce1;
    linear_weights_4_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address0;
    linear_weights_4_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_address1;
    linear_weights_4_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce0;
    linear_weights_4_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_4_ce1;
    linear_weights_5_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address0;
    linear_weights_5_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_address1;
    linear_weights_5_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce0;
    linear_weights_5_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_5_ce1;
    linear_weights_6_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address0;
    linear_weights_6_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_address1;
    linear_weights_6_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce0;
    linear_weights_6_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_6_ce1;
    linear_weights_7_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address0;
    linear_weights_7_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_address1;
    linear_weights_7_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce0;
    linear_weights_7_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_7_ce1;
    linear_weights_8_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address0;
    linear_weights_8_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_address1;
    linear_weights_8_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce0;
    linear_weights_8_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_8_ce1;
    linear_weights_9_address0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address0;
    linear_weights_9_address1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_address1;
    linear_weights_9_ce0 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce0;
    linear_weights_9_ce1 <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_linear_weights_9_ce1;
    or_ln46_fu_532_p2 <= (icmp_ln46_fu_520_p2 or icmp_ln46_1_fu_526_p2);
    output_r_din <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_din;

    output_r_write_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            output_r_write <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_output_r_write;
        else 
            output_r_write <= ap_const_logic_0;
        end if; 
    end process;


    pool_output_read_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read, ap_CS_fsm_state9)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
            pool_output_read <= grp_inference_Pipeline_VITIS_LOOP_76_1_fu_457_pool_output_read;
        else 
            pool_output_read <= ap_const_logic_0;
        end if; 
    end process;


    pool_output_write_assign_proc : process(grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            pool_output_write <= grp_inference_Pipeline_VITIS_LOOP_54_1_fu_449_pool_output_write;
        else 
            pool_output_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln86_1_fu_516_p1 <= pool_stride(31 - 1 downto 0);
    trunc_ln86_fu_512_p1 <= pool_size(31 - 1 downto 0);
end behav;
